name: gaspolapp
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:

  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_staggered_grid_view: "^0.2.5"
  flutter_speedometer: ^1.0.2
  speedometer: "^1.0.1"
  fluttertoast: ^3.1.3
  splashscreen: ^1.2.0
  get_it: ^1.0.3+2
  url_launcher: ^5.0.3
  http: ^0.12.0+2
  dio: ^2.0.22
  shared_preferences: ^0.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
   android: "launcher_icon"
   ios: true
   image_path: "assets/icon_apk.png"



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
  - assets/

fonts:
     - family: axiforma
       fonts:
         - asset: assets/fonts/axiforma_regular.ttf
         - asset: assets/fonts/axiforma_thin.ttf